# Generated by Django 4.2.3 on 2023-08-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerstudent',
            name='image',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
    ]
